apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: postgresql
  template:
    metadata:
      labels:
        deployment: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:11.6
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: postgresdb
        - name: PGDATA
          value: /var/lib/postgresql/data
        - name: max_connections
          value: '1000'
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - name: postgres-ps
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-ps
        persistentVolumeClaim:
          claimName: postgresql-pv-claim
