apiVersion: v1
kind: Service
metadata:
  name: am-service
spec:
  ports:
  - name: http9443
    port: 9443
    targetPort: 9443
  - name: http8243
    port: 8243
    targetPort: 8243
  - name: http8280
    port: 8280
    targetPort: 8280
  selector:
    deployment: wso2am
  type: NodePort